coverage:
  ignore:
    - "tests/*"
    - "**/*/__init__.py"
    - "nomenclate_api/db/*.py"
    - "nomenclate_api/api_spec"
    - "nomenclate_api/openapi_plugin"
    - "nomenclate_api/utils/responses"
    - "nomenclate_api/schemas"
