[tool.poetry]
name = "nomenclate-api"
version = "0.1.0"
description = "Simple Python project built with Poetry."
authors = ["Andres Weber <andresmweber@gmail.com>"]
maintainers = ["Todd Birchard <toddbirchard@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = ""
repository = "https://github.com/hackersandslackers/python-poetry-tutorial/"
documentation = "https://hackersandslackers.com/python-poetry/"
keywords = [
    "Poetry",
    "Virtual Environments",
    "Tutorial",
    "Packages",
    "Packaging"
]

[tool.poetry.dependencies]
python = "^3.6"
nomenclate = "^2.4.4"
google-cloud-storage = "^1.38.0"
Flask = "^1.1.2"
firebase-admin = "^4.5.3"
pymongo = "^3.11.3"
python-dotenv = "^0.17.0"
dnspython = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
poethepoet = "^0.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
run = "wsgi:main"

[tool.poetry.urls]
issues = "https://github.com/andresmweber/nomenclate-api/issues"

[tool.poe.tasks]
test            = "pytest --cov=poethepoet"                                                              # simple command based task
freeze          = { shell = "poetry export -f requirements.txt > requirements.txt --without-hashes" }    # shell script based task
mksandwich      = { script = "my_package.sandwich:build" }                                               # python script based task
deploy          = { shell = "sls deploy" }                                                               
deploy-domain   = { shell = "SLS_DEBUG=* sls create_domain" }                                     
dev             = { shell = "sls wsgi serve" }
