name: Sync OAS to ReadMe
on:
  workflow_run:
    workflows: ["CI/CD"]
    branches:
      - main
      - master
    types:
      - completed
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.6
      - name: Install dependencies
        run: poetry install
      - name: Update documentation
        run: poetry run docs
      - uses: readmeio/github-readme-sync@v2
        with:
          readme-oas-key: ${{ secrets.README_API_KEY }}
          oas-file-path: ./docs/spec/json/nomenclate.json
          # api-version: 'v1.0.0'
